[package]
name = "rs-wndws"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-link-lib = ["main"]
rustc-link-search = ["./"]
